version: 2
jobs:
  build:
    docker:
      - image: zenspider/emacs-ruby:latest
    working_directory: ~/package
    steps:
      - checkout
      - run: emacs --batch -Q -l tests.el -f ert-run-tests-batch-and-exit
